### PR TITLE
Adding support for lock keypads and get pins

### PR DESCRIPTION
**Pull request by rjames86**
The `get_lock_detail` already returns information about the keypad if one is installed. Adding support for keypad information on `LockDetail` when it's available.

Also adding a new endpoint to get information about keypad pins.

### CODE REVIEW

**Comment by snjoetw** [comment]
Thanks! Are you planning to integrate this into HASS?

**Comment by rjames86** [comment]
@snjoetw I hadn't planned on it, but might look into it. I'm building out a little app for managing an Airbnb, and I want to be able to get/create pin codes from a computer. I'll probably send out more PRs as I figure out more of August's API

**Comment by snjoetw** [comment]
Ok I'll see if I have time to integrate it myself over the weekend

**Comment by snjoetw** [comment]
@rjames86 do you have an example response payload for `/locks/{lock_id}/pins` API ? If so can you share the payload with me (with sensitive data removed) please?
I'd like to refactor the code a bit so it conforms lint rule but I need to write a test for it first

**Comment by rjames86** [comment]
@snjoetw Here's my Typescript interface for the pins response

https://github.com/rjames86/airbnb/blob/master/types/august.d.ts#L46-L75

If you need something with a little more detail, let me know

**Comment by snjoetw** [comment]
Thanks!

**Comment by snjoetw** [comment]
I just pushed the change to fix lint errors: https://github.com/snjoetw/py-august/commit/02d62a8f127ce5ef47d971c5cc5d46f8f37b930b

The change is mainly to change camel case to snake case in pin.py, hopefully this won't break your stuff :)

**Pull request merged**
