### PR TITLE
Add support for refreshing access token

### PR DESCRIPTION
**Pull request by sidoh**
Firstly -- thanks for putting together this library.  I use the HASS August integration heavily, and am very grateful for your work.

## Motivation

Access tokens expire after three months.  The last time I had to delete the cache and reboot HomeAssistant, I decided I'd dig into whether this was necessary (after all, the August app doesn't require you to re-login).

Looks like this can be avoided.  

## Background

I dug around in mitmproxy and noticed that API responses always include a `x-august-access-token` header with a fresh access token.  Observations:

* By decoding the token (it's a JWT), you can see that the expiration of this token will be three months from the time the request is made, regardless of when the the token was originally issued.
* The next request coming from the August app will use the token contained in the response of the previous one.

Looks like this is how the August app is keeping tokens fresh.

## Summary of Changes

I added two methods:

* `Api.refresh_access_token(self, access_token)`: makes a call to an arbitrary GET endpoint (right now`/users/houses/mine`) and returns the access token from the response.
* `Authenticator.refresh_access_token(self, force=False)`: checks whether the token will expire within 7 days (threshold is configurable in the constructor).  If not, returns the current `Authentication` object.  If so, it refreshes the token by:
  * Calling `refresh_access_token` on the `Api` object.
  * Extracting the expiration time from the JWT claims
  * Constructing and returning a new `Authentication` object

## Followups

In order for this to have any affect on HomeAssistant, we'd have to update it to make use of the new methods.

I'm not familiar enough with HomeAssistant's internals to know if this is a bad idea, but it seems like a simple change would be to change this:

```python
hass.data[DATA_AUGUST] = AugustData(hass, api, authentication.access_token)
```

to this:

```python
hass.data[DATA_AUGUST] = AugustData(hass, api, authentication)
```

and then use the new `authentication.refresh_access_token()` method somewhere.

### CODE REVIEW

**Comment by sidoh** [comment]
@snjoetw, obviously no rush, but wanted check if you have any thoughts here.  

Hoping we'll be able to fix tokens expiring on the folks using the HomeAssistant August component =)

**Comment by TonyBrobston** [comment]
I'm currently having this exact problem, hoping for a fix. Thanks to everyone that works on these projects!

**Comment by snjoetw** [comment]
Thanks for the PR! I'll include this in 0.9.0

**Comment by snjoetw** [comment]
Correction: this is in 0.10.0: https://pypi.org/project/py-august/0.10.0/

**Comment by bdraco** [comment]
Looks like this may cause

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/august/__init__.py", line 161, in setup
    access_token_cache_file=hass.config.path(AUGUST_CONFIG_FILE),
  File "/usr/local/lib/python3.7/site-packages/august/authenticator.py", line 110, in __init__
    if self._authentication.is_expired():
  File "/usr/local/lib/python3.7/site-packages/august/authenticator.py", line 76, in is_expired
    return self.parsed_expiration_time() < datetime.utcnow()
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Pull request merged**
