### PR TITLE
Fix august token refresh

### PR DESCRIPTION
**Pull request by bdraco**
I had a refactoring error when I convert this to async.

Fixes https://github.com/home-assistant/core/issues/39526

### CODE REVIEW

**Comment by bdraco** [comment]
@snjoetw Can you take a look ?

**Comment by bdraco** [comment]
@snjoetw not sure if you are seeing these or super busy and can't get to this?

**Comment by bdraco** [comment]
@snjoetw Any chance you have a moment to take a look at this ?

**Comment by ai-write-city** [comment]
Thanks @bdraco, merged

**Comment by bdraco** [comment]
Thanks.  Can you push out a new release so I can bump home assistant?

**Comment by ai-write-city** [comment]
Just released 0.25.1: https://pypi.org/project/py-august/0.25.1/

**Comment by snjoetw** [comment]
@bdraco please use 0.25.2 instead: https://github.com/snjoetw/py-august/releases/tag/0.25.2

**Comment by bdraco** [comment]
Thanks updated https://github.com/home-assistant/core/pull/40109

**Pull request merged**
