### PR TITLE
Handle 429

### PR DESCRIPTION
**Pull request by bdraco**
There is probably a better way to solve this, however this did it for my needs.

https://github.com/home-assistant/home-assistant/issues/31472

### CODE REVIEW

**Comment by niemyjski** [comment]
Lgtm

**Comment by snjoetw** [comment]
merged thanks! @bdraco are you also gonna update hass to uptake the new version?

**Comment by snjoetw** [comment]
I published 0.8.1: https://pypi.org/project/py-august/0.8.1/

**Comment by snjoetw** [comment]
@bdraco fyi I released 0.10.0 with https://github.com/snjoetw/py-august/pull/23 as well

**Comment by bdraco** [comment]
> merged thanks! @bdraco are you also gonna update hass to uptake the new version?

Working on this now (redoing the existing PR as I can now remove some things)

Thank you!

**Comment by bdraco** [comment]
> @bdraco fyi I released 0.10.0 with #23 as well

Unfortunately, it looks like 0.10.0 has a bug in time zone comparison.  I sent in a PR to fix it
https://github.com/snjoetw/py-august/pull/25

**Pull request merged**
